name: pet_family_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_svg: ^2.0.0
  brasil_fields: ^1.17.0
  pinput: ^5.0.1
  google_maps_flutter: ^2.2.3
  flutter_native_splash: ^2.4.6
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2
  dio: ^5.9.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

flutter_native_splash:
  color: "#42a5f5"
  image: assets/logos/logo.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center


dev_dependencies:
  test: ^1.24.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
  
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Light.ttf
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-Medium.ttf